# version: '3.8'

services:
  mongo:
    image: mongodb/mongodb-community-server
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: qwer1234
    ports:
      - 27017:27017
    volumes:
      - /root/user-service/mongo-data:/data/db

volumes:
  mongo-data: